# Generated by Django 5.2.18 on 2026-10-10 15:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("texts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_id",
                    models.CharField(
                        help_text="e.g. JHN.1.12.s1", max_length=24, unique=True
                    ),
                ),
                ("book", models.CharField(max_length=3)),
                ("chapter", models.PositiveSmallIntegerField()),
                ("verse", models.PositiveSmallIntegerField(help_text="First verse")),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Sentence number within the first verse"
                    ),
                ),
                (
                    "refs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        help_text="Verse ids the sentence covers",
                        size=None,
                    ),
                ),
                ("source_text_id", models.CharField(max_length=32)),
                (
                    "tokens",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        help_text="Source word ids, in order",
                        size=None,
                    ),
                ),
                ("source_text", models.TextField(blank=True)),
                ("literal_gloss", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ai_draft", "AI draft"),
                            ("meaning_reviewed", "Meaning reviewed"),
                            ("reviewed", "Reviewed"),
                            ("revised", "Revised"),
                        ],
                        default="ai_draft",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="texts.edition"
                    ),
                ),
            ],
            options={
                "ordering": ["book", "chapter", "verse", "number"],
            },
        ),
        migrations.CreateModel(
            name="ReviewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("meaning_reviewed", "Approved the meaning"),
                            ("reviewed", "Approved the wording"),
                            ("revised", "Revised after review"),
                            ("flagged", "Flagged a problem"),
                            ("comment", "Comment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, help_text="For wording reviews", max_length=3
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_events",
                        to="translation.sentence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rendering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(help_text="e.g. en, es", max_length=3)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("L", "Literal"),
                            ("B", "Balanced"),
                            ("R", "Readable"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="May contain {{setting:default|alt}} spans and \\v markers"
                    ),
                ),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renderings",
                        to="translation.sentence",
                    ),
                ),
            ],
            options={
                "ordering": ["sentence", "language", "level"],
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(help_text="e.g. m1, r-en-2", max_length=16)),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("meaning", "Meaning (shared by every language)"),
                            ("rendering", "Rendering (one language)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Blank for meaning decisions",
                        max_length=3,
                    ),
                ),
                (
                    "levels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("category", models.CharField(max_length=24)),
                (
                    "tokens",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("choice", models.TextField()),
                (
                    "alternatives",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("reason", models.TextField()),
                ("uncertain", models.BooleanField(default=False)),
                ("footnote", models.BooleanField(default=False)),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="translation.sentence",
                    ),
                ),
            ],
            options={
                "ordering": ["sentence", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="sentence",
            index=models.Index(
                fields=["book", "chapter"], name="translation_book_b01165_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rendering",
            constraint=models.UniqueConstraint(
                fields=("sentence", "language", "level"),
                name="one_rendering_per_language_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="decision",
            constraint=models.UniqueConstraint(
                fields=("sentence", "key"), name="unique_decision_key"
            ),
        ),
    ]
