# Generated by Django 5.2.18 on 2026-10-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="e.g. sblgnt, wlc, bsb, rv1909",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "language",
                    models.CharField(
                        help_text="ISO 639-3: grc, hbo, eng, spa", max_length=3
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("original", "Original-language base text"),
                            ("reference", "Reference translation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("licence", models.CharField(max_length=200)),
                (
                    "source",
                    models.CharField(
                        help_text="Key in sources.lock.json", max_length=64
                    ),
                ),
                ("source_commit", models.CharField(max_length=40)),
                ("source_path", models.CharField(blank=True, max_length=200)),
                ("attribution", models.TextField(blank=True)),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["kind", "language", "code"],
            },
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book", models.CharField(max_length=3)),
                ("chapter", models.PositiveSmallIntegerField()),
                ("verse", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="texts.edition",
                    ),
                ),
            ],
            options={
                "ordering": ["edition", "book", "chapter", "verse"],
                "indexes": [
                    models.Index(
                        fields=["book", "chapter"], name="texts_verse_book_2c4429_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edition", "book", "chapter", "verse"),
                        name="unique_verse_per_edition",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("book", models.CharField(max_length=3)),
                ("chapter", models.PositiveSmallIntegerField()),
                ("verse", models.PositiveSmallIntegerField()),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Word number within the verse"
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(help_text="Order within the edition"),
                ),
                ("text", models.CharField(max_length=64)),
                ("after", models.CharField(blank=True, max_length=16)),
                ("lemma", models.CharField(blank=True, max_length=64)),
                ("morph", models.CharField(blank=True, max_length=32)),
                ("gloss", models.CharField(blank=True, max_length=200)),
                ("english", models.CharField(blank=True, max_length=200)),
                ("strong", models.CharField(blank=True, max_length=16)),
                ("transliteration", models.CharField(blank=True, max_length=64)),
                (
                    "lang",
                    models.CharField(
                        blank=True,
                        help_text="grc, H (Hebrew) or A (Aramaic)",
                        max_length=3,
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="texts.edition",
                    ),
                ),
            ],
            options={
                "ordering": ["seq"],
                "indexes": [
                    models.Index(
                        fields=["book", "chapter", "verse"],
                        name="texts_word_book_3a831b_idx",
                    )
                ],
            },
        ),
    ]
